#!/usr/bin/env bash

# Description: Run fd/find in subtree and list files by mime type in smart context
# Dependencies: fd/find
#
# Shell: POSIX compliant supporting mktemp
# Author: Arun Prakash Jana

. "$(dirname "$0")"/.nnn-plugin-helper

if [ "$(cmd_exists fd)" -eq "0" ]; then
	fd=fd
else
	fd=find
fi

printf "mime: "
read -r mime

nnn_tmp=$(mktemp "/tmp/nnnXXXXXX")

$fd | file -if- | grep "$mime" | awk -F: '{printf "%s\0", $1}' > "$nnn_tmp"
printf "+l%s" "$nnn_tmp" > "$NNN_PIPE"
